In [274]:
import numpy as np
import pandas as pd
from flask import Flask, request, jsonify, render_template
import pickle
import joblib
import json
from tensorflow import keras
from flask_cors import CORS
from sklearn.preprocessing import StandardScaler, LabelEncoder
le = LabelEncoder()


In [275]:
# Create flask app
flask_app = Flask(__name__)
CORS(flask_app)
model =keras.models.load_model("my_h5_model.h5")
# model = pickle.load(open("model.pkl","rb"))

In [276]:
@flask_app.route("/")
def Home():
    return render_template("index.html")

In [277]:
@flask_app.route("/predict2", methods = ["POST"])
def predict():
    pkl_file = open('Departure_encoder.pkl', 'rb')
    le_departure = pickle.load(pkl_file) 
    pkl_file.close()
    x = request.get_json()["result_arr"]
    y = pd.DataFrame(columns=["N" , "P" , "K","temperature" , "humidity","ph","rainfall" ])
    y.loc[0]=x
    print("Y=",y )

#     y = json.loads(x)
    

    prediction = model.predict(y)
    max3_values = np.argsort(prediction[0])[::-1]
    classes = le_departure.inverse_transform(max3_values)
    print(max3_values)
    print(prediction.tostring())
# #     return render_template("index.html", prediction_text = "The flower species is {}".format(prediction))
#     return render_template("index.html", value = json.dumps({prediction}))
    return jsonify(result=prediction.tolist()[0] , indexes=max3_values.tolist() , classes=classes.tolist())

In [ ]:
if __name__ == "__main__":
    flask_app.run(debug=True,use_reloader=False , host="0.0.0.0")

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   Use a production WSGI server instead.
 * Debug mode: on


 * Running on all addresses.
 * Running on http://192.168.43.185:5000/ (Press CTRL+C to quit)
192.168.43.205 - - [31/Aug/2022 09:14:02] "OPTIONS //predict2 HTTP/1.1" 200 -
192.168.43.205 - - [31/Aug/2022 09:14:02] "OPTIONS //predict2 HTTP/1.1" 200 -


Y=       N     P     K  temperature  humidity   ph  rainfall
0  40.0  20.0  80.0         25.0       NaN  6.0      80.6
Y=       N     P     K  temperature  humidity   ph  rainfall
0  40.0  20.0  80.0         25.0       NaN  6.0      80.6
1/1 [==============================] - 0s 152ms/step


C:\Users\Expert Info\AppData\Local\Temp\ipykernel_5248\6600134.py:18: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  print(prediction.tostring())
192.168.43.205 - - [31/Aug/2022 09:14:02] "POST //predict2 HTTP/1.1" 200 -
192.168.43.205 - - [31/Aug/2022 09:14:02] "POST //predict2 HTTP/1.1" 200 -


[21 20  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19  0]
b'\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f'
[21 20  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19  0]
b'\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f'


192.168.43.205 - - [31/Aug/2022 09:14:45] "OPTIONS //predict2 HTTP/1.1" 200 -
192.168.43.205 - - [31/Aug/2022 09:14:45] "OPTIONS //predict2 HTTP/1.1" 200 -


Y=       N     P     K temperature humidity    ph rainfall
0  None  None  None        None     None  None     None
Y=       N     P     K temperature humidity    ph rainfall
0  None  None  None        None     None  None     None


192.168.43.205 - - [31/Aug/2022 09:14:45] "POST //predict2 HTTP/1.1" 500 -
192.168.43.205 - - [31/Aug/2022 09:14:45] "Traceback (most recent call last):
  File "C:\anaconda3\Lib\site-packages\tensorflow\python\data\util\structure.py", line 102, in normalize_element
    spec = type_spec_from_value(t, use_fallback=False)
  File "C:\anaconda3\Lib\site-packages\tensorflow\python\data\util\structure.py", line 485, in type_spec_from_value
    raise TypeError("Could not build a `TypeSpec` for {} with type {}".format(
TypeError: Could not build a `TypeSpec` for       N     P     K temperature humidity    ph rainfall
0  None  None  None        None     None  None     None with type DataFrame

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\anaconda3\Lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\anaconda3\Lib\site-packages\flask\app.py", line 2450, in wsgi_app

Y=        N     P     K  temperature   humidity        ph   rainfall
0  134.0  56.0  18.0    23.808346  83.919026  6.691268  70.973583
Y=        N     P     K  temperature   humidity        ph   rainfall
0  134.0  56.0  18.0    23.808346  83.919026  6.691268  70.973583
1/1 [==============================] - 0s 42ms/step


C:\Users\Expert Info\AppData\Local\Temp\ipykernel_5248\6600134.py:18: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  print(prediction.tostring())
192.168.43.205 - - [31/Aug/2022 09:15:27] "POST //predict2 HTTP/1.1" 200 -
192.168.43.205 - - [31/Aug/2022 09:15:27] "POST //predict2 HTTP/1.1" 200 -


[ 6 11  7 15  1  5  2 12 17  8 13  3 21 20 14 10 18 16 19  0  9  4]
b'\x1c6\x81\'\xa0\xec\xc36l\nH6\xe1\xba+4\t\xf0@\x1a\x16\xb8\xaf6\xca\x99~?\x85U\xa98\x98\xbdq5\x08\x0fv\'\xad\xc7\x8c/8\xe2\xae;:(-6\xaf\xc2w4\x001D0\x96)\xec7i\x8ck)\x98\xe0\x056F"\x07+\xee\xa8\x0e)\xd2\x7f\x1f3\xc9\x98\xac3'
[ 6 11  7 15  1  5  2 12 17  8 13  3 21 20 14 10 18 16 19  0  9  4]
b'\x1c6\x81\'\xa0\xec\xc36l\nH6\xe1\xba+4\t\xf0@\x1a\x16\xb8\xaf6\xca\x99~?\x85U\xa98\x98\xbdq5\x08\x0fv\'\xad\xc7\x8c/8\xe2\xae;:(-6\xaf\xc2w4\x001D0\x96)\xec7i\x8ck)\x98\xe0\x056F"\x07+\xee\xa8\x0e)\xd2\x7f\x1f3\xc9\x98\xac3'


192.168.43.205 - - [31/Aug/2022 09:16:50] "OPTIONS //predict2 HTTP/1.1" 200 -
192.168.43.205 - - [31/Aug/2022 09:16:50] "OPTIONS //predict2 HTTP/1.1" 200 -


Y=       N     P     K  temperature   humidity        ph   rainfall
0  20.0  56.0  90.0          NaN  83.919026  6.691268  70.973583
Y=       N     P     K  temperature   humidity        ph   rainfall
0  20.0  56.0  90.0          NaN  83.919026  6.691268  70.973583
1/1 [==============================] - 0s 49ms/step


C:\Users\Expert Info\AppData\Local\Temp\ipykernel_5248\6600134.py:18: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  print(prediction.tostring())
192.168.43.205 - - [31/Aug/2022 09:16:50] "POST //predict2 HTTP/1.1" 200 -
192.168.43.205 - - [31/Aug/2022 09:16:50] "POST //predict2 HTTP/1.1" 200 -


[21 20  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19  0]
b'\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f'
[21 20  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19  0]
b'\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f'


192.168.43.205 - - [31/Aug/2022 09:17:09] "OPTIONS //predict2 HTTP/1.1" 200 -
192.168.43.205 - - [31/Aug/2022 09:17:09] "OPTIONS //predict2 HTTP/1.1" 200 -


Y=       N     P     K  temperature   humidity        ph   rainfall
0  20.0  56.0  90.0          NaN  83.919026  6.691268  70.973583
Y=       N     P     K  temperature   humidity        ph   rainfall
0  20.0  56.0  90.0          NaN  83.919026  6.691268  70.973583
1/1 [==============================] - 0s 44ms/step


C:\Users\Expert Info\AppData\Local\Temp\ipykernel_5248\6600134.py:18: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  print(prediction.tostring())
192.168.43.205 - - [31/Aug/2022 09:17:10] "POST //predict2 HTTP/1.1" 200 -
192.168.43.205 - - [31/Aug/2022 09:17:10] "POST //predict2 HTTP/1.1" 200 -


[21 20  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19  0]
b'\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f'
[21 20  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19  0]
b'\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f\x00\x00\xc0\x7f'


192.168.43.205 - - [31/Aug/2022 09:18:04] "OPTIONS //predict2 HTTP/1.1" 200 -
192.168.43.205 - - [31/Aug/2022 09:18:04] "OPTIONS //predict2 HTTP/1.1" 200 -


Y=       N     P     K  temperature   humidity        ph   rainfall
0  20.0  56.0  90.0        15.22  83.919026  6.691268  70.973583
Y=       N     P     K  temperature   humidity        ph   rainfall
0  20.0  56.0  90.0        15.22  83.919026  6.691268  70.973583
1/1 [==============================] - 0s 47ms/step


C:\Users\Expert Info\AppData\Local\Temp\ipykernel_5248\6600134.py:18: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  print(prediction.tostring())
192.168.43.205 - - [31/Aug/2022 09:18:04] "POST //predict2 HTTP/1.1" 200 -


[19 17  0 14  7 13  1 10 21 15  2 12  3  8  6 11  4 20  9 18 16  5]
b"\xc7\x87\xa2=\xaaM)6=T\xf44vJ'3\x0c\xa7\xba1\x9c\x89\x13&\x89^\xfd1\x1a\xab\x847\xf6z\xa22\xe5l/-7B\x126\x9b\xbb\xce1\xa3w\x1b4\xaf\x08(7\xb6J'8\xe96@5\x18-\xfe'\xab\x1a'>\x87\x01\x14*\x87\xe3A?_\x1bo.F\x7f\xee5"
1/1 [==============================] - 0s 70ms/step


192.168.43.205 - - [31/Aug/2022 09:18:04] "POST //predict2 HTTP/1.1" 200 -


[19 17  0 14  7 13  1 10 21 15  2 12  3  8  6 11  4 20  9 18 16  5]
b"\xc7\x87\xa2=\xaaM)6=T\xf44vJ'3\x0c\xa7\xba1\x9c\x89\x13&\x89^\xfd1\x1a\xab\x847\xf6z\xa22\xe5l/-7B\x126\x9b\xbb\xce1\xa3w\x1b4\xaf\x08(7\xb6J'8\xe96@5\x18-\xfe'\xab\x1a'>\x87\x01\x14*\x87\xe3A?_\x1bo.F\x7f\xee5"


192.168.43.205 - - [31/Aug/2022 09:19:47] "OPTIONS //predict2 HTTP/1.1" 200 -
192.168.43.205 - - [31/Aug/2022 09:19:47] "OPTIONS //predict2 HTTP/1.1" 200 -


Y=       N     P     K  temperature   humidity        ph   rainfall
0  20.0  56.0  90.0        25.22  70.919026  6.691268  90.973583
Y=       N     P     K  temperature   humidity        ph   rainfall
0  20.0  56.0  90.0        25.22  70.919026  6.691268  90.973583
1/1 [==============================] - 0s 42ms/step


C:\Users\Expert Info\AppData\Local\Temp\ipykernel_5248\6600134.py:18: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  print(prediction.tostring())
192.168.43.205 - - [31/Aug/2022 09:19:48] "POST //predict2 HTTP/1.1" 200 -
192.168.43.205 - - [31/Aug/2022 09:19:48] "POST //predict2 HTTP/1.1" 200 -


[17  0 19 12  7 13  3 21 14  2  4  1  8 10  6  9 15 20 18 11 16  5]
b"r\xff\xa2=}T\xdf4M_\x815\xa1U\xa87e\xec\x025\xef\x1b\x14'i\x1fV2w5\xfc8)\xd8\xcc3<4\xf71\xd1gT37J\xae.={\xfe9\xcbW\xc38\x874\xbe6<\xbb 1nFy(\xd1rb?z\xffk/z\xd3\x0f=\xa9(\x82/\x87z\xd66"
[17  0 19 12  7 13  3 21 14  2  4  1  8 10  6  9 15 20 18 11 16  5]
b"r\xff\xa2=}T\xdf4M_\x815\xa1U\xa87e\xec\x025\xef\x1b\x14'i\x1fV2w5\xfc8)\xd8\xcc3<4\xf71\xd1gT37J\xae.={\xfe9\xcbW\xc38\x874\xbe6<\xbb 1nFy(\xd1rb?z\xffk/z\xd3\x0f=\xa9(\x82/\x87z\xd66"


192.168.43.205 - - [31/Aug/2022 09:23:00] "OPTIONS //predict2 HTTP/1.1" 200 -
192.168.43.205 - - [31/Aug/2022 09:23:00] "OPTIONS //predict2 HTTP/1.1" 200 -


Y=       N     P      K  temperature   humidity        ph   rainfall
0  20.0  56.0  150.0    23.808346  87.919026  5.691268  80.973583
Y=       N     P      K  temperature   humidity        ph   rainfall
0  20.0  56.0  150.0    23.808346  87.919026  5.691268  80.973583
1/1 [==============================] - 0s 55ms/step


C:\Users\Expert Info\AppData\Local\Temp\ipykernel_5248\6600134.py:18: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  print(prediction.tostring())
192.168.43.205 - - [31/Aug/2022 09:23:01] "POST //predict2 HTTP/1.1" 200 -


[17  0 19  7  3 14 12 15 13 21  1  6  2  8  4 20 10  9 11 18  5 16]
b'rP\xf7>f\x18D37h\t0\xb9\n\xaf5\xe1]l,\x15\xdf\xd5\x1a\xfe\xa0"1\xaeJ\x10:j\x7f\xb0-\xbf\xa5\x9b(\xaa\nA*W\xc5W(\xaf\xeea4\x1cC\x174\xbb\xfd\x9a4\xbcGI4\x1d\xf4\x9d\x1a\xbb\x05\x03?\xf9VS\x1e\xb7\xe9\x96;D\xcd,+\xf3\xb5\xb93'
1/1 [==============================] - 0s 45ms/step


192.168.43.205 - - [31/Aug/2022 09:23:01] "POST //predict2 HTTP/1.1" 200 -


[17  0 19  7  3 14 12 15 13 21  1  6  2  8  4 20 10  9 11 18  5 16]
b'rP\xf7>f\x18D37h\t0\xb9\n\xaf5\xe1]l,\x15\xdf\xd5\x1a\xfe\xa0"1\xaeJ\x10:j\x7f\xb0-\xbf\xa5\x9b(\xaa\nA*W\xc5W(\xaf\xeea4\x1cC\x174\xbb\xfd\x9a4\xbcGI4\x1d\xf4\x9d\x1a\xbb\x05\x03?\xf9VS\x1e\xb7\xe9\x96;D\xcd,+\xf3\xb5\xb93'


192.168.43.205 - - [31/Aug/2022 09:23:54] "OPTIONS //predict2 HTTP/1.1" 200 -
192.168.43.205 - - [31/Aug/2022 09:23:54] "OPTIONS //predict2 HTTP/1.1" 200 -


Y=       N     P      K  temperature   humidity        ph   rainfall
0  40.0  56.0  150.0    33.808346  77.919026  5.691268  80.973583
Y=       N     P      K  temperature   humidity        ph   rainfall
0  40.0  56.0  150.0    33.808346  77.919026  5.691268  80.973583
1/1 [==============================] - 0s 37ms/step


C:\Users\Expert Info\AppData\Local\Temp\ipykernel_5248\6600134.py:18: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  print(prediction.tostring())
192.168.43.205 - - [31/Aug/2022 09:23:54] "POST //predict2 HTTP/1.1" 200 -
192.168.43.205 - - [31/Aug/2022 09:23:54] "POST //predict2 HTTP/1.1" 200 -


[17  0  7  3  1 15 21 13 19 12 14  6  2  8 20  4 11  9 10 18  5 16]
b"\xa8\xd6\x03=\xb8\x18\xb68j\x1df1\x16\n\xa3;\x1d\xc1c+\xda\xe7\xf1\x1d)\x93\xb02\xca-><x\x0b(1\x02y\xa3*\x8e\xa1#*\xae\xa3\x1b+\xce*\xc85\xc6\x18\x8e7\xce\xe5\x833'3&8L\xab$\x1b\xe2ws?b\x04\xc7 \xc0H\xb86=\xab!.W\x91\x028"
[17  0  7  3  1 15 21 13 19 12 14  6  2  8 20  4 11  9 10 18  5 16]
b"\xa8\xd6\x03=\xb8\x18\xb68j\x1df1\x16\n\xa3;\x1d\xc1c+\xda\xe7\xf1\x1d)\x93\xb02\xca-><x\x0b(1\x02y\xa3*\x8e\xa1#*\xae\xa3\x1b+\xce*\xc85\xc6\x18\x8e7\xce\xe5\x833'3&8L\xab$\x1b\xe2ws?b\x04\xc7 \xc0H\xb86=\xab!.W\x91\x028"


192.168.43.205 - - [31/Aug/2022 09:25:14] "OPTIONS //predict2 HTTP/1.1" 200 -
192.168.43.205 - - [31/Aug/2022 09:25:14] "OPTIONS //predict2 HTTP/1.1" 200 -


Y=       N     P      K  temperature   humidity        ph   rainfall
0  40.0  56.0  150.0    33.808346  77.919026  5.691268  80.973583
Y=       N     P      K  temperature   humidity        ph   rainfall
0  40.0  56.0  150.0    33.808346  77.919026  5.691268  80.973583
1/1 [==============================] - 0s 32ms/step


C:\Users\Expert Info\AppData\Local\Temp\ipykernel_5248\6600134.py:18: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  print(prediction.tostring())
192.168.43.205 - - [31/Aug/2022 09:25:15] "POST //predict2 HTTP/1.1" 200 -
192.168.43.205 - - [31/Aug/2022 09:25:15] "POST //predict2 HTTP/1.1" 200 -


[17  0  7  3  1 15 21 13 19 12 14  6  2  8 20  4 11  9 10 18  5 16]
b"\xa8\xd6\x03=\xb8\x18\xb68j\x1df1\x16\n\xa3;\x1d\xc1c+\xda\xe7\xf1\x1d)\x93\xb02\xca-><x\x0b(1\x02y\xa3*\x8e\xa1#*\xae\xa3\x1b+\xce*\xc85\xc6\x18\x8e7\xce\xe5\x833'3&8L\xab$\x1b\xe2ws?b\x04\xc7 \xc0H\xb86=\xab!.W\x91\x028"
[17  0  7  3  1 15 21 13 19 12 14  6  2  8 20  4 11  9 10 18  5 16]
b"\xa8\xd6\x03=\xb8\x18\xb68j\x1df1\x16\n\xa3;\x1d\xc1c+\xda\xe7\xf1\x1d)\x93\xb02\xca-><x\x0b(1\x02y\xa3*\x8e\xa1#*\xae\xa3\x1b+\xce*\xc85\xc6\x18\x8e7\xce\xe5\x833'3&8L\xab$\x1b\xe2ws?b\x04\xc7 \xc0H\xb86=\xab!.W\x91\x028"


192.168.43.205 - - [31/Aug/2022 09:26:48] "OPTIONS //predict2 HTTP/1.1" 200 -
192.168.43.205 - - [31/Aug/2022 09:26:48] "OPTIONS //predict2 HTTP/1.1" 200 -


Y=       N     P      K  temperature   humidity        ph   rainfall
0  70.0  56.0  150.0    33.808346  77.919026  5.691268  80.973583
Y=       N     P      K  temperature   humidity        ph   rainfall
0  70.0  56.0  150.0    33.808346  77.919026  5.691268  80.973583
1/1 [==============================] - 0s 41ms/step


C:\Users\Expert Info\AppData\Local\Temp\ipykernel_5248\6600134.py:18: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  print(prediction.tostring())
192.168.43.205 - - [31/Aug/2022 09:26:48] "POST //predict2 HTTP/1.1" 200 -
192.168.43.205 - - [31/Aug/2022 09:26:48] "POST //predict2 HTTP/1.1" 200 -


[ 1 21 17  7  3 15  0 13  8  6 12 19 11  2 14 20 10  4  9  5 18 16]
b'\xcf:\x129\xdb\xb9b?};\xdc0\x0b\x8d-;\xba\xd2q\'\x02\r\xd2!\xb1\x05:3\xce\x99\x01<\xa5\x0f 5\x99\x12\x1b\'\x02\xb5})\x8ab\x021o\xab\xdc2"\xcd\xbe8\xe3\xd8\xb10\x1b\xa3\xeb:\x9dc\x7f\x1c\x1b\xd4\x1a=\xefM\x81\x1d*6[1\x1a\xfe\x93/\xba\xff\x82='
[ 1 21 17  7  3 15  0 13  8  6 12 19 11  2 14 20 10  4  9  5 18 16]
b'\xcf:\x129\xdb\xb9b?};\xdc0\x0b\x8d-;\xba\xd2q\'\x02\r\xd2!\xb1\x05:3\xce\x99\x01<\xa5\x0f 5\x99\x12\x1b\'\x02\xb5})\x8ab\x021o\xab\xdc2"\xcd\xbe8\xe3\xd8\xb10\x1b\xa3\xeb:\x9dc\x7f\x1c\x1b\xd4\x1a=\xefM\x81\x1d*6[1\x1a\xfe\x93/\xba\xff\x82='


192.168.43.205 - - [31/Aug/2022 09:28:14] "OPTIONS //predict2 HTTP/1.1" 200 -
192.168.43.205 - - [31/Aug/2022 09:28:14] "OPTIONS //predict2 HTTP/1.1" 200 -


Y=       N     P      K  temperature   humidity        ph   rainfall
0  40.0  56.0  150.0    33.808346  77.919026  4.691268  75.973583
Y=       N     P      K  temperature   humidity        ph   rainfall
0  40.0  56.0  150.0    33.808346  77.919026  4.691268  75.973583
1/1 [==============================] - 0s 48ms/step


C:\Users\Expert Info\AppData\Local\Temp\ipykernel_5248\6600134.py:18: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  print(prediction.tostring())
192.168.43.205 - - [31/Aug/2022 09:28:14] "POST //predict2 HTTP/1.1" 200 -
192.168.43.205 - - [31/Aug/2022 09:28:14] "POST //predict2 HTTP/1.1" 200 -


[17  7  0  3 15  1 21 13 19 12 14  6  2  8 20 11  4  9 10 18  5 16]
b'\xd5\x17\xb0<6@\x149\xa5A\x191w\x9e\xa7;\xc7)\xa8*\xb6:\x05\x1e\x85A\xfe2\xa7}\xba<\x07\xd1\x071\x00s\x81*\x80\x136*-\xed\x1e+\x18\xf7\x025\xd3\r\x957Y+\x853\x88=\x199U\xf5\x7f\x1a*Fs?\xbb}a J\x01-6\x11\xe33.\x91D\xdb7'
[17  7  0  3 15  1 21 13 19 12 14  6  2  8 20 11  4  9 10 18  5 16]
b'\xd5\x17\xb0<6@\x149\xa5A\x191w\x9e\xa7;\xc7)\xa8*\xb6:\x05\x1e\x85A\xfe2\xa7}\xba<\x07\xd1\x071\x00s\x81*\x80\x136*-\xed\x1e+\x18\xf7\x025\xd3\r\x957Y+\x853\x88=\x199U\xf5\x7f\x1a*Fs?\xbb}a J\x01-6\x11\xe33.\x91D\xdb7'


192.168.43.205 - - [31/Aug/2022 09:29:10] "OPTIONS //predict2 HTTP/1.1" 200 -
192.168.43.205 - - [31/Aug/2022 09:29:10] "OPTIONS //predict2 HTTP/1.1" 200 -


Y=       N     P      K  temperature   humidity        ph   rainfall
0  20.0  56.0  150.0    23.808346  83.919026  6.691268  70.973583
Y=       N     P      K  temperature   humidity        ph   rainfall
0  20.0  56.0  150.0    23.808346  83.919026  6.691268  70.973583
1/1 [==============================] - 0s 59ms/step


C:\Users\Expert Info\AppData\Local\Temp\ipykernel_5248\6600134.py:18: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  print(prediction.tostring())
192.168.43.205 - - [31/Aug/2022 09:29:10] "POST //predict2 HTTP/1.1" 200 -


[17  0  7 19  3 15 14 13  1 21 12  6  2  8 20  4  9 10 11 18  5 16]
b'\xe3\xbd\xc7>\xe1\xd5\xeb4\x10)\xd0/\x81\xf4:7*>\x7f+\xe2Y\x91\x1c\x11582\x9c\x9b\x07="\xaf"/\x98\xfb\xdd)&u\xc6)\xd9\x84\xc3(\tH\xba3\x05\x92\x055\xa14\xc45n\xbf\x026 \x92\xcb\x19A\x8e\x13?X\\\x94\x1e\xd6W\xc09X $,\xae\x93O4'
1/1 [==============================] - 0s 35ms/step


192.168.43.205 - - [31/Aug/2022 09:29:10] "POST //predict2 HTTP/1.1" 200 -


[17  0  7 19  3 15 14 13  1 21 12  6  2  8 20  4  9 10 11 18  5 16]
b'\xe3\xbd\xc7>\xe1\xd5\xeb4\x10)\xd0/\x81\xf4:7*>\x7f+\xe2Y\x91\x1c\x11582\x9c\x9b\x07="\xaf"/\x98\xfb\xdd)&u\xc6)\xd9\x84\xc3(\tH\xba3\x05\x92\x055\xa14\xc45n\xbf\x026 \x92\xcb\x19A\x8e\x13?X\\\x94\x1e\xd6W\xc09X $,\xae\x93O4'


192.168.43.205 - - [31/Aug/2022 09:29:53] "OPTIONS //predict2 HTTP/1.1" 200 -
192.168.43.205 - - [31/Aug/2022 09:29:53] "OPTIONS //predict2 HTTP/1.1" 200 -


Y=       N     P      K  temperature   humidity        ph   rainfall
0  40.0  56.0  150.0    33.808346  77.919026  4.691268  75.973583
Y=       N     P      K  temperature   humidity        ph   rainfall
0  40.0  56.0  150.0    33.808346  77.919026  4.691268  75.973583
1/1 [==============================] - 0s 51ms/step


C:\Users\Expert Info\AppData\Local\Temp\ipykernel_5248\6600134.py:18: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  print(prediction.tostring())
192.168.43.205 - - [31/Aug/2022 09:29:53] "POST //predict2 HTTP/1.1" 200 -


[17  7  0  3 15  1 21 13 19 12 14  6  2  8 20 11  4  9 10 18  5 16]
b'\xd5\x17\xb0<6@\x149\xa5A\x191w\x9e\xa7;\xc7)\xa8*\xb6:\x05\x1e\x85A\xfe2\xa7}\xba<\x07\xd1\x071\x00s\x81*\x80\x136*-\xed\x1e+\x18\xf7\x025\xd3\r\x957Y+\x853\x88=\x199U\xf5\x7f\x1a*Fs?\xbb}a J\x01-6\x11\xe33.\x91D\xdb7'
1/1 [==============================] - 0s 47ms/step


192.168.43.205 - - [31/Aug/2022 09:29:53] "POST //predict2 HTTP/1.1" 200 -


[17  7  0  3 15  1 21 13 19 12 14  6  2  8 20 11  4  9 10 18  5 16]
b'\xd5\x17\xb0<6@\x149\xa5A\x191w\x9e\xa7;\xc7)\xa8*\xb6:\x05\x1e\x85A\xfe2\xa7}\xba<\x07\xd1\x071\x00s\x81*\x80\x136*-\xed\x1e+\x18\xf7\x025\xd3\r\x957Y+\x853\x88=\x199U\xf5\x7f\x1a*Fs?\xbb}a J\x01-6\x11\xe33.\x91D\xdb7'


192.168.43.205 - - [31/Aug/2022 09:30:42] "OPTIONS //predict2 HTTP/1.1" 200 -
192.168.43.205 - - [31/Aug/2022 09:30:42] "OPTIONS //predict2 HTTP/1.1" 200 -


Y=       N     P      K  temperature   humidity        ph   rainfall
0  40.0  56.0  150.0    23.808346  83.919026  4.691268  80.973583Y=       N     P      K  temperature   humidity        ph   rainfall
0  40.0  56.0  150.0    23.808346  83.919026  4.691268  80.973583

1/1 [==============================] - 0s 45ms/step


C:\Users\Expert Info\AppData\Local\Temp\ipykernel_5248\6600134.py:18: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  print(prediction.tostring())
192.168.43.205 - - [31/Aug/2022 09:30:43] "POST //predict2 HTTP/1.1" 200 -


[17  0  7  1 19 21  3 15 13 12 14  6  2  8 11 20  4 10  9  5 18 16]
b'E\xd3\x80>\x8f\x89\xba9q\xca\x8f1\x96\xf5\xcc8C\xaa\xfc+\xe5\x86O\x1e\xa6\xc6\xce2\x14q=;\x96\xf3=1\xa1V\x02)\xfd\xb5\xa8*\xcf\x9cF.\xac\xf8\x1c4yv\x1f6-\xd7\xda3W\xf1\x0c8g\xdb\xf4\x1c\x80\x9c>?-\xfe\xed\x1d\xe4`\xad9\xee\xe5".d\xfa\xd48'
1/1 [==============================] - 0s 41ms/step


192.168.43.205 - - [31/Aug/2022 09:30:43] "POST //predict2 HTTP/1.1" 200 -


[17  0  7  1 19 21  3 15 13 12 14  6  2  8 11 20  4 10  9  5 18 16]
b'E\xd3\x80>\x8f\x89\xba9q\xca\x8f1\x96\xf5\xcc8C\xaa\xfc+\xe5\x86O\x1e\xa6\xc6\xce2\x14q=;\x96\xf3=1\xa1V\x02)\xfd\xb5\xa8*\xcf\x9cF.\xac\xf8\x1c4yv\x1f6-\xd7\xda3W\xf1\x0c8g\xdb\xf4\x1c\x80\x9c>?-\xfe\xed\x1d\xe4`\xad9\xee\xe5".d\xfa\xd48'


192.168.43.205 - - [31/Aug/2022 09:31:44] "OPTIONS //predict2 HTTP/1.1" 200 -
192.168.43.205 - - [31/Aug/2022 09:31:44] "OPTIONS //predict2 HTTP/1.1" 200 -


Y=       N     P      K  temperature   humidity        ph   rainfall
0  40.0  56.0  190.0    23.808346  73.919026  6.691268  80.973583
Y=       N     P      K  temperature   humidity        ph   rainfall
0  40.0  56.0  190.0    23.808346  73.919026  6.691268  80.973583
1/1 [==============================] - 0s 42ms/step


C:\Users\Expert Info\AppData\Local\Temp\ipykernel_5248\6600134.py:18: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  print(prediction.tostring())
192.168.43.205 - - [31/Aug/2022 09:31:45] "POST //predict2 HTTP/1.1" 200 -
192.168.43.205 - - [31/Aug/2022 09:31:45] "POST //predict2 HTTP/1.1" 200 -


[ 7 17  3  0  1 15 21 13  6 14 12 19  8 20  2  9 11  4 10  5 18 16][ 7 17  3  0  1 15 21 13  6 14 12 19  8 20  2  9 11  4 10  5 18 16]

b'\xed9\x0e:\x16\x84\xc97\xfc\xff")\x15\xfdI:\x05\x0c\x04#\x06\x84\xd9\x17\x8ay\x9b07\x86~?]\xf1\xba-\xb1\x9e\x11&\xa8\xbc\x9d\x1b!\x84\x8b$\xf3\xfa\xa7/n\x83\x141\xa0\x08\xe8/\x1c\xc8\x024jJ\xa1\r\x97\x11\x91;\x9e\x03\xa7\x11\xd5\x035/\xa4\x93\xd9)\xfb\xf2\xa33'
b'\xed9\x0e:\x16\x84\xc97\xfc\xff")\x15\xfdI:\x05\x0c\x04#\x06\x84\xd9\x17\x8ay\x9b07\x86~?]\xf1\xba-\xb1\x9e\x11&\xa8\xbc\x9d\x1b!\x84\x8b$\xf3\xfa\xa7/n\x83\x141\xa0\x08\xe8/\x1c\xc8\x024jJ\xa1\r\x97\x11\x91;\x9e\x03\xa7\x11\xd5\x035/\xa4\x93\xd9)\xfb\xf2\xa33'


192.168.43.205 - - [31/Aug/2022 09:32:39] "OPTIONS //predict2 HTTP/1.1" 200 -
192.168.43.205 - - [31/Aug/2022 09:32:39] "OPTIONS //predict2 HTTP/1.1" 200 -


Y=       N     P      K  temperature   humidity        ph   rainfall
0  60.0  96.0  190.0    33.808346  83.919026  5.691268  80.973583
Y=       N     P      K  temperature   humidity        ph   rainfall
0  60.0  96.0  190.0    33.808346  83.919026  5.691268  80.973583
1/1 [==============================] - 0s 49ms/step


C:\Users\Expert Info\AppData\Local\Temp\ipykernel_5248\6600134.py:18: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  print(prediction.tostring())
192.168.43.205 - - [31/Aug/2022 09:32:40] "POST //predict2 HTTP/1.1" 200 -
192.168.43.205 - - [31/Aug/2022 09:32:40] "POST //predict2 HTTP/1.1" 200 -


[ 7  3  1 17  0 15 21 13  8 14  6 12 19  2  9 11 20 10  4 18  5 16][ 7  3  1 17  0 15 21 13  8 14  6 12 19  2  9 11 20 10  4 18  5 16]
b'\xf8\xf2\xe68\xed\xf9\x10;pa\x10(\x11s3=\x1e\xc3\xf1\x1ckC\xc8\x139nI+o\xa1s?c!\xb8,\x0c\xe2\x9e&\x99\xbea"1sD&$~\xe6*\x03\xc0\xea1U/~,J\x1c\xf46\'g\xaf\t4\xa8\x0e;L\x7f\x01\x16\xa4\xf1\xec)C+*&_rE5'

b'\xf8\xf2\xe68\xed\xf9\x10;pa\x10(\x11s3=\x1e\xc3\xf1\x1ckC\xc8\x139nI+o\xa1s?c!\xb8,\x0c\xe2\x9e&\x99\xbea"1sD&$~\xe6*\x03\xc0\xea1U/~,J\x1c\xf46\'g\xaf\t4\xa8\x0e;L\x7f\x01\x16\xa4\xf1\xec)C+*&_rE5'


192.168.43.205 - - [31/Aug/2022 09:33:38] "OPTIONS //predict2 HTTP/1.1" 200 -
192.168.43.205 - - [31/Aug/2022 09:33:38] "OPTIONS //predict2 HTTP/1.1" 200 -


Y=       N     P      K  temperature   humidity        ph   rainfall
0  40.0  26.0  140.0    23.808346  73.919026  5.691268  80.973583
Y=       N     P      K  temperature   humidity        ph   rainfall
0  40.0  26.0  140.0    23.808346  73.919026  5.691268  80.973583
1/1 [==============================] - 0s 58ms/step


C:\Users\Expert Info\AppData\Local\Temp\ipykernel_5248\6600134.py:18: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  print(prediction.tostring())
192.168.43.205 - - [31/Aug/2022 09:33:38] "POST //predict2 HTTP/1.1" 200 -


[17  0 19 21  7  1 12  6 13 15  3 14  8  2 20 11  4 10  9  5 16 18]
b'\x8f\x9e\xed=\x9d"!:\xf1\x10\x194M\xbdQ7\xc6\xb2\x97/\x8fg$%\xfb\x04\xd08\x93Nt:\x81m\x9f4\xc7\xa1S(\xc5\x18\x08*M\xd0\xe2/\xa9\xd6^9\x9e\xc9\xbd8\xd4\xc3\x985\xb6\xd698\xaf7\xbf#(\xfc]?~\x17>\x1e284<H\xe5\x8c2\xdc\x98{;'
1/1 [==============================] - 0s 39ms/step


192.168.43.205 - - [31/Aug/2022 09:33:38] "POST //predict2 HTTP/1.1" 200 -


[17  0 19 21  7  1 12  6 13 15  3 14  8  2 20 11  4 10  9  5 16 18]
b'\x8f\x9e\xed=\x9d"!:\xf1\x10\x194M\xbdQ7\xc6\xb2\x97/\x8fg$%\xfb\x04\xd08\x93Nt:\x81m\x9f4\xc7\xa1S(\xc5\x18\x08*M\xd0\xe2/\xa9\xd6^9\x9e\xc9\xbd8\xd4\xc3\x985\xb6\xd698\xaf7\xbf#(\xfc]?~\x17>\x1e284<H\xe5\x8c2\xdc\x98{;'


192.168.43.205 - - [31/Aug/2022 09:35:34] "OPTIONS //predict2 HTTP/1.1" 200 -
192.168.43.205 - - [31/Aug/2022 09:35:34] "OPTIONS //predict2 HTTP/1.1" 200 -


Y=       N     P      K  temperature    humidity        ph    rainfall
0  80.0  26.0  140.0    27.808346  123.919026  5.691268  100.973583
Y=       N     P      K  temperature    humidity        ph    rainfall
0  80.0  26.0  140.0    27.808346  123.919026  5.691268  100.973583
1/1 [==============================] - 0s 38ms/step


C:\Users\Expert Info\AppData\Local\Temp\ipykernel_5248\6600134.py:18: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  print(prediction.tostring())
192.168.43.205 - - [31/Aug/2022 09:35:34] "POST //predict2 HTTP/1.1" 200 -


[21 17 19  1 13 15  7 12 14  0  6  8 11  2  3 20  4 10 16  5  9 18]
b"\xea<r4\xea\x0bk8\xf1\x8b\x122\x8d\xa9P-\xa0o:+\xb1\x84\xd4#\xf3\x08\xb73\xb0\xf5\x9f5u\xe9\xa63\x88\xa7\xde\x1b\x94\xdd\xd9*\xa6[\x9c2mn\x055W\x18\xdb7\x08\xfc\xce4\x81F:7[\x1fQ'\x00d\xd3<\xaf\x9ai\x19-A\xf3;\x14\xb6\x00,\x17xw?"
1/1 [==============================] - 0s 37ms/step


192.168.43.205 - - [31/Aug/2022 09:35:34] "POST //predict2 HTTP/1.1" 200 -


[21 17 19  1 13 15  7 12 14  0  6  8 11  2  3 20  4 10 16  5  9 18]
b"\xea<r4\xea\x0bk8\xf1\x8b\x122\x8d\xa9P-\xa0o:+\xb1\x84\xd4#\xf3\x08\xb73\xb0\xf5\x9f5u\xe9\xa63\x88\xa7\xde\x1b\x94\xdd\xd9*\xa6[\x9c2mn\x055W\x18\xdb7\x08\xfc\xce4\x81F:7[\x1fQ'\x00d\xd3<\xaf\x9ai\x19-A\xf3;\x14\xb6\x00,\x17xw?"


192.168.43.205 - - [31/Aug/2022 09:36:38] "OPTIONS //predict2 HTTP/1.1" 200 -
192.168.43.205 - - [31/Aug/2022 09:36:38] "OPTIONS //predict2 HTTP/1.1" 200 -


Y=       N     P      K  temperature    humidity        ph    rainfall
0  80.0  66.0  140.0    27.808346  123.919026  5.691268  100.973583
Y=       N     P      K  temperature    humidity        ph    rainfall
0  80.0  66.0  140.0    27.808346  123.919026  5.691268  100.973583
1/1 [==============================] - 0s 45ms/step


C:\Users\Expert Info\AppData\Local\Temp\ipykernel_5248\6600134.py:18: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  print(prediction.tostring())
192.168.43.205 - - [31/Aug/2022 09:36:39] "POST //predict2 HTTP/1.1" 200 -
192.168.43.205 - - [31/Aug/2022 09:36:39] "POST //predict2 HTTP/1.1" 200 -


[17 21  1 15  0 19  7 13 11 14  6  8  2 12  3 10 20  4 16  9  5 18]
b'\xbd\x0c69Y#\x85<;\x14\xcd2\xed\xa3R1\xad\x15\xb2(\x8f\x95" \xf0\xb4j3\xdf\x9b\xa17\xea273\xf2!B \xb2\xf8\x14/\x1ao\xcb3\xdb\x1f\x811BP\x897!\xe4\x833\x8di\x8b:p\xe8s!V\xe4S?\xb2[\'\x1aZ\'-9f\xbb\xb4-0Q\x1e>'
[17 21  1 15  0 19  7 13 11 14  6  8  2 12  3 10 20  4 16  9  5 18]
b'\xbd\x0c69Y#\x85<;\x14\xcd2\xed\xa3R1\xad\x15\xb2(\x8f\x95" \xf0\xb4j3\xdf\x9b\xa17\xea273\xf2!B \xb2\xf8\x14/\x1ao\xcb3\xdb\x1f\x811BP\x897!\xe4\x833\x8di\x8b:p\xe8s!V\xe4S?\xb2[\'\x1aZ\'-9f\xbb\xb4-0Q\x1e>'


192.168.43.205 - - [31/Aug/2022 09:37:29] "OPTIONS //predict2 HTTP/1.1" 200 -
192.168.43.205 - - [31/Aug/2022 09:37:29] "OPTIONS //predict2 HTTP/1.1" 200 -


Y=       N     P      K  temperature   humidity        ph    rainfall
0  80.0  66.0  140.0    27.808346  80.919026  5.691268  100.973583
Y=       N     P      K  temperature   humidity        ph    rainfall
0  80.0  66.0  140.0    27.808346  80.919026  5.691268  100.973583
1/1 [==============================] - 0s 53ms/step


C:\Users\Expert Info\AppData\Local\Temp\ipykernel_5248\6600134.py:18: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  print(prediction.tostring())
192.168.43.205 - - [31/Aug/2022 09:37:30] "POST //predict2 HTTP/1.1" 200 -


[ 1 21 17  7  3  0 15 13  8 11 12  6 19  2 20 14 10  9  4  5 16 18]
b"\xbb+/7\x8dny?\x14\x18\x8b/\xb2\x1a\xb68\x00DE'e\xefK!\\\t71\xc2;G9\x94b\x185-h\x94'\xc6|\xaa(\x82\xd3]2[E>1\xe1\x0b\xbb5P1\xc3-\x8d\x15\xc06.F\xda\x1d\x07\xb6\x13;\x05\xc7/\x1cnh\x8705\xf4:.\xe3L\xbd<"
1/1 [==============================] - 0s 46ms/step


192.168.43.205 - - [31/Aug/2022 09:37:30] "POST //predict2 HTTP/1.1" 200 -


[ 1 21 17  7  3  0 15 13  8 11 12  6 19  2 20 14 10  9  4  5 16 18]
b"\xbb+/7\x8dny?\x14\x18\x8b/\xb2\x1a\xb68\x00DE'e\xefK!\\\t71\xc2;G9\x94b\x185-h\x94'\xc6|\xaa(\x82\xd3]2[E>1\xe1\x0b\xbb5P1\xc3-\x8d\x15\xc06.F\xda\x1d\x07\xb6\x13;\x05\xc7/\x1cnh\x8705\xf4:.\xe3L\xbd<"


192.168.43.205 - - [31/Aug/2022 09:38:35] "OPTIONS //predict2 HTTP/1.1" 200 -
192.168.43.205 - - [31/Aug/2022 09:38:35] "OPTIONS //predict2 HTTP/1.1" 200 -


Y=       N     P      K  temperature    humidity        ph    rainfall
0  80.0  66.0  140.0    27.808346  100.919026  6.691268  100.973583
Y=       N     P      K  temperature    humidity        ph    rainfall
0  80.0  66.0  140.0    27.808346  100.919026  6.691268  100.973583
1/1 [==============================] - 0s 37ms/step
[ 1 21 17 15  0  7 13 19  8  3 11  6  2 12 14 20 10  4  9  5 16 18]
b'V=\n9q\x11B?-\x18\xcc1\xa7m>5_!\x89(\xe1\x1e1"\xdefa3\xe9\xa0\xf98\xb6\xf4\xc559m\x9f$\xf8\xad\x1b-Glg4\x8fu\xb51;"\x977\xabo\x191\xa6\xda\xbc9\xab\x1d\xa2 unx=\xf3I\xc9\x1b\xfc\xdc\x036/\xb7+/\x8c\xf88>'


C:\Users\Expert Info\AppData\Local\Temp\ipykernel_5248\6600134.py:18: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  print(prediction.tostring())
192.168.43.205 - - [31/Aug/2022 09:38:35] "POST //predict2 HTTP/1.1" 200 -
192.168.43.205 - - [31/Aug/2022 09:38:35] "POST //predict2 HTTP/1.1" 200 -


[ 1 21 17 15  0  7 13 19  8  3 11  6  2 12 14 20 10  4  9  5 16 18]
b'V=\n9q\x11B?-\x18\xcc1\xa7m>5_!\x89(\xe1\x1e1"\xdefa3\xe9\xa0\xf98\xb6\xf4\xc559m\x9f$\xf8\xad\x1b-Glg4\x8fu\xb51;"\x977\xabo\x191\xa6\xda\xbc9\xab\x1d\xa2 unx=\xf3I\xc9\x1b\xfc\xdc\x036/\xb7+/\x8c\xf88>'


192.168.43.205 - - [31/Aug/2022 09:49:49] "OPTIONS //predict2 HTTP/1.1" 200 -
192.168.43.205 - - [31/Aug/2022 09:49:49] "OPTIONS //predict2 HTTP/1.1" 200 -


Y=       N     P      K  temperature    humidity        ph    rainfall
0  80.0  66.0  140.0    27.808346  100.919026  6.691268  100.973583
Y=       N     P      K  temperature    humidity        ph    rainfall
0  80.0  66.0  140.0    27.808346  100.919026  6.691268  100.973583
1/1 [==============================] - 0s 40ms/step


C:\Users\Expert Info\AppData\Local\Temp\ipykernel_5248\6600134.py:18: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  print(prediction.tostring())
192.168.43.205 - - [31/Aug/2022 09:49:50] "POST //predict2 HTTP/1.1" 200 -


[ 1 21 17 15  0  7 13 19  8  3 11  6  2 12 14 20 10  4  9  5 16 18]
b'V=\n9q\x11B?-\x18\xcc1\xa7m>5_!\x89(\xe1\x1e1"\xdefa3\xe9\xa0\xf98\xb6\xf4\xc559m\x9f$\xf8\xad\x1b-Glg4\x8fu\xb51;"\x977\xabo\x191\xa6\xda\xbc9\xab\x1d\xa2 unx=\xf3I\xc9\x1b\xfc\xdc\x036/\xb7+/\x8c\xf88>'
1/1 [==============================] - 0s 34ms/step


192.168.43.205 - - [31/Aug/2022 09:49:50] "POST //predict2 HTTP/1.1" 200 -


[ 1 21 17 15  0  7 13 19  8  3 11  6  2 12 14 20 10  4  9  5 16 18]
b'V=\n9q\x11B?-\x18\xcc1\xa7m>5_!\x89(\xe1\x1e1"\xdefa3\xe9\xa0\xf98\xb6\xf4\xc559m\x9f$\xf8\xad\x1b-Glg4\x8fu\xb51;"\x977\xabo\x191\xa6\xda\xbc9\xab\x1d\xa2 unx=\xf3I\xc9\x1b\xfc\xdc\x036/\xb7+/\x8c\xf88>'


192.168.43.205 - - [31/Aug/2022 10:29:10] "OPTIONS //predict2 HTTP/1.1" 200 -
192.168.43.205 - - [31/Aug/2022 10:29:10] "OPTIONS //predict2 HTTP/1.1" 200 -


Y=       N     P      K  temperature    humidity        ph    rainfall
0  80.0  66.0  140.0    27.808346  100.919026  6.691268  100.973583
Y=       N     P      K  temperature    humidity        ph    rainfall
0  80.0  66.0  140.0    27.808346  100.919026  6.691268  100.973583
1/1 [==============================] - 0s 20ms/step


C:\Users\Expert Info\AppData\Local\Temp\ipykernel_5248\6600134.py:18: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  print(prediction.tostring())
192.168.43.205 - - [31/Aug/2022 10:29:11] "POST //predict2 HTTP/1.1" 200 -
192.168.43.205 - - [31/Aug/2022 10:29:11] "POST //predict2 HTTP/1.1" 200 -


[ 1 21 17 15  0  7 13 19  8  3 11  6  2 12 14 20 10  4  9  5 16 18][ 1 21 17 15  0  7 13 19  8  3 11  6  2 12 14 20 10  4  9  5 16 18]
b'V=\n9q\x11B?-\x18\xcc1\xa7m>5_!\x89(\xe1\x1e1"\xdefa3\xe9\xa0\xf98\xb6\xf4\xc559m\x9f$\xf8\xad\x1b-Glg4\x8fu\xb51;"\x977\xabo\x191\xa6\xda\xbc9\xab\x1d\xa2 unx=\xf3I\xc9\x1b\xfc\xdc\x036/\xb7+/\x8c\xf88>'

b'V=\n9q\x11B?-\x18\xcc1\xa7m>5_!\x89(\xe1\x1e1"\xdefa3\xe9\xa0\xf98\xb6\xf4\xc559m\x9f$\xf8\xad\x1b-Glg4\x8fu\xb51;"\x977\xabo\x191\xa6\xda\xbc9\xab\x1d\xa2 unx=\xf3I\xc9\x1b\xfc\xdc\x036/\xb7+/\x8c\xf88>'


192.168.43.205 - - [31/Aug/2022 10:48:17] "OPTIONS //predict2 HTTP/1.1" 200 -
192.168.43.205 - - [31/Aug/2022 10:48:17] "OPTIONS //predict2 HTTP/1.1" 200 -


Y=       N     P      K  temperature    humidity        ph    rainfall
0  80.0  66.0  140.0    27.808346  100.919026  6.691268  100.973583
Y=       N     P      K  temperature    humidity        ph    rainfall
0  80.0  66.0  140.0    27.808346  100.919026  6.691268  100.973583
1/1 [==============================] - 0s 15ms/step


C:\Users\Expert Info\AppData\Local\Temp\ipykernel_5248\6600134.py:18: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  print(prediction.tostring())
192.168.43.205 - - [31/Aug/2022 10:48:17] "POST //predict2 HTTP/1.1" 200 -


[ 1 21 17 15  0  7 13 19  8  3 11  6  2 12 14 20 10  4  9  5 16 18]
b'V=\n9q\x11B?-\x18\xcc1\xa7m>5_!\x89(\xe1\x1e1"\xdefa3\xe9\xa0\xf98\xb6\xf4\xc559m\x9f$\xf8\xad\x1b-Glg4\x8fu\xb51;"\x977\xabo\x191\xa6\xda\xbc9\xab\x1d\xa2 unx=\xf3I\xc9\x1b\xfc\xdc\x036/\xb7+/\x8c\xf88>'
1/1 [==============================] - 0s 16ms/step


192.168.43.205 - - [31/Aug/2022 10:48:17] "POST //predict2 HTTP/1.1" 200 -


[ 1 21 17 15  0  7 13 19  8  3 11  6  2 12 14 20 10  4  9  5 16 18]
b'V=\n9q\x11B?-\x18\xcc1\xa7m>5_!\x89(\xe1\x1e1"\xdefa3\xe9\xa0\xf98\xb6\xf4\xc559m\x9f$\xf8\xad\x1b-Glg4\x8fu\xb51;"\x977\xabo\x191\xa6\xda\xbc9\xab\x1d\xa2 unx=\xf3I\xc9\x1b\xfc\xdc\x036/\xb7+/\x8c\xf88>'
